global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nurtricenter-patient'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api:8080']
        labels:
          service: 'nurtricenter-patient'

  - job_name: 'consul'
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['consul:8500']
